[package]
edition = "2021"
name    = "miden-node-panic-macro"
version = "0.11.0"

[lib]
proc-macro = true

[dependencies]
anyhow  = { workspace = true }
futures = { workspace = true }
quote   = "1"
syn     = { features = ["full"], version = "2" }
tracing = { workspace = true }
